#!/bin/sh


set -e


echo "Installing strap (Homebrew ecosystem)"
cd ~
git clone https://github.com/MikeMcQuaid/strap
cd strap
sh strap.sh

echo "Cloning personal dotfiles"
cd ~
git clone https://github.com/theand/mathiasdotfiles

