#!/bin/sh



set -e

##comment out due to duplicated with strap.sh
### grabbed from https://github.com/donnemartin/dev-setup/blob/master/osxprep.sh
### start
## Keep-alive: update existing `sudo` time stamp until `bootstrap` has finished
#while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
#
#
#echo "Updating OSX. If this requires a restart, run the script again."
## Install all available updates
#sudo softwareupdate -ia --restart --verbose
#
#echo "Installing Xcode Command Line Tools."
#xcode-select --install
### end
#




## grabbed from https://github.com/bkuhlmann/mac_os-config/blob/master/bin/apply_basic_settings
## start
# Applies basic system settings.

read -p "What is this machine's name (Example: \"alchemist\")? " mac_os_name
if [[ -z "$mac_os_name" ]]; then
  printf "ERROR: Invalid MacOS name.\n"
  exit 1
fi

printf "Setting system name...\n"
sudo scutil --set ComputerName $mac_os_name
sudo scutil --set LocalHostName $mac_os_name
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $mac_os_name
## end

